---
name: "TubeArchivistMetadataByIsop"
guid: "ecf7cb0e-59d9-463c-84db-4a076c833014"
imageUrl: https://raw.githubusercontent.com/IvanSop/tubearchivist-jf-plugin/master/images/logo.png
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Metadata for your TubeArchivist library on Jellyfin"
description: >
  TubeArchivistMetadata is a plugin that automatically manages
  metadata for videos downloaded with TubeArchivist from YouTube.

  This is a fork of the original plugin by DarkFighterLuke.
category: "Metadata"
owner: "IvanSop"
artifacts:
- "Jellyfin.Plugin.TubeArchivistMetadata.dll"
changelog: >
  Local metadata provider to get embedded TA metadata from video files.
